// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyt5bznWm5Kmad2Jp45gD0akUAlbY-07Q',
    appId: '1:886106181787:web:1d05b986c43142611df63e',
    messagingSenderId: '886106181787',
    projectId: 'talipapa-ef93a',
    authDomain: 'talipapa-ef93a.firebaseapp.com',
    storageBucket: 'talipapa-ef93a.firebasestorage.app',
    measurementId: 'G-LCLXHQTNTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZD4h7Gc3wCkdGyUe4Q9qAUYpxB7gw0k',
    appId: '1:886106181787:android:5bc506839b0165fd1df63e',
    messagingSenderId: '886106181787',
    projectId: 'talipapa-ef93a',
    storageBucket: 'talipapa-ef93a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jFm5fETu-NQa9uIQMWTpQeL7aqcLXiQ',
    appId: '1:886106181787:ios:8da463a025e304cb1df63e',
    messagingSenderId: '886106181787',
    projectId: 'talipapa-ef93a',
    storageBucket: 'talipapa-ef93a.firebasestorage.app',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4jFm5fETu-NQa9uIQMWTpQeL7aqcLXiQ',
    appId: '1:886106181787:ios:8da463a025e304cb1df63e',
    messagingSenderId: '886106181787',
    projectId: 'talipapa-ef93a',
    storageBucket: 'talipapa-ef93a.firebasestorage.app',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyt5bznWm5Kmad2Jp45gD0akUAlbY-07Q',
    appId: '1:886106181787:web:02cd858d0eb90c851df63e',
    messagingSenderId: '886106181787',
    projectId: 'talipapa-ef93a',
    authDomain: 'talipapa-ef93a.firebaseapp.com',
    storageBucket: 'talipapa-ef93a.firebasestorage.app',
    measurementId: 'G-F8K50HYEY0',
  );
}
