// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0VWeWu3tIKzBWKWUbHYiUnhPZyVOFpG4',
    appId: '1:255870757274:web:73dfbaec748ff882ae7223',
    messagingSenderId: '255870757274',
    projectId: 'talipapa-4777f',
    authDomain: 'talipapa-4777f.firebaseapp.com',
    storageBucket: 'talipapa-4777f.firebasestorage.app',
    measurementId: 'G-ZJ9N8E6EPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATPBYKlzMbJR4JNYPDh-FzhykLXXs1W24',
    appId: '1:255870757274:android:a43e38ee22b1fd78ae7223',
    messagingSenderId: '255870757274',
    projectId: 'talipapa-4777f',
    storageBucket: 'talipapa-4777f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIUbRyBjaSmRxd35x9ZtRcXAk04fbpiZY',
    appId: '1:255870757274:ios:ae306cece578a404ae7223',
    messagingSenderId: '255870757274',
    projectId: 'talipapa-4777f',
    storageBucket: 'talipapa-4777f.firebasestorage.app',
    iosBundleId: 'com.example.Talipapa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIUbRyBjaSmRxd35x9ZtRcXAk04fbpiZY',
    appId: '1:255870757274:ios:ae306cece578a404ae7223',
    messagingSenderId: '255870757274',
    projectId: 'talipapa-4777f',
    storageBucket: 'talipapa-4777f.firebasestorage.app',
    iosBundleId: 'com.example.Talipapa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0VWeWu3tIKzBWKWUbHYiUnhPZyVOFpG4',
    appId: '1:255870757274:web:01dd4566fdfb3c79ae7223',
    messagingSenderId: '255870757274',
    projectId: 'talipapa-4777f',
    authDomain: 'talipapa-4777f.firebaseapp.com',
    storageBucket: 'talipapa-4777f.firebasestorage.app',
    measurementId: 'G-BPGVPYKWHB',
  );
}
